package it.unina.ingSw.cineMates20.utils;

public enum NameResources {
    CSS_CLASS_INPUT_ERROR,
    DIRECTORY_FXML,

    LOGIN_LAYOUT,
    HOME_LAYOUT,
    NAVIGATION_MENU_LAYOUT,
    REPORT_MOVIE_ITEM_LAYOUT,
    REPORT_USER_ITEM_LAYOUT,
    REPORT_USERS_CONTAINER_DETAILS_LAYOUT,
    REPORT_MOVIES_CONTAINER_DETAILS_LAYOUT,

    DB_PATH,
    ADMIN_PATH,
    GET_PSW_HASH_PATH,
    EMAIL_ALREADY_EXISTS_PATH,
    GET_BASIC_ADMIN_INFO_PATH,
    REPORT_PATH,
    UPDATE_MOVIE_REPORT_PATH,

    IAM_ACCESS_KEY,
    IAM_SECRET_KEY,
    S3_BUCKET_NAME,

    TMDB_API_KEY,
    FIRST_PATH_IMAGE,
    FIRST_PATH_IMAGE_ORIGINAL,

    LOGGED_USER_EMAIL
}
